# Generated by Django 2.2.5 on 2019-09-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='环境名称')),
                ('tag', models.CharField(max_length=10, unique=True, verbose_name='环境标识')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '环境管理',
                'verbose_name_plural': '环境管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='机房名称')),
                ('tag', models.CharField(max_length=20, unique=True, verbose_name='机房标识')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '机房管理',
                'verbose_name_plural': '机房管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='项目名称')),
                ('tag', models.CharField(max_length=10, unique=True, verbose_name='项目标识')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('number', models.CharField(max_length=20, verbose_name='工号')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('cpu', models.CharField(max_length=10, verbose_name='CPU(C)')),
                ('memory', models.CharField(max_length=10, verbose_name='内存(G)')),
                ('model', models.CharField(default=None, max_length=100, verbose_name='型号')),
                ('virtual', models.CharField(default='KVM', max_length=20, verbose_name='虚拟化技术')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '维护'), (2, '损坏')], default=0, verbose_name='状态')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asset.User', verbose_name='管理员')),
            ],
            options={
                'verbose_name': '物理机管理',
                'verbose_name_plural': '物理机管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='主机名')),
                ('lan', models.GenericIPAddressField(unique=True, verbose_name='内网地址')),
                ('wan', models.GenericIPAddressField(blank=True, help_text='可选', null=True, verbose_name='外网地址')),
                ('use', models.CharField(max_length=100, verbose_name='用途')),
                ('cpu', models.CharField(max_length=10, verbose_name='CPU(C)')),
                ('memory', models.CharField(max_length=10, verbose_name='内存(G)')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '维护'), (2, '损坏')], default=0, verbose_name='状态')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asset.User', verbose_name='管理员')),
                ('env', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asset.Env', verbose_name='环境')),
                ('idc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asset.Idc', verbose_name='机房')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Project', verbose_name='项目')),
                ('server', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Server', verbose_name='物理机')),
            ],
            options={
                'verbose_name': '虚拟机管理',
                'verbose_name_plural': '虚拟机管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20, verbose_name='资产编号')),
                ('unit', models.IntegerField(choices=[(0, '计算机主机'), (1, '计算机显示器'), (2, '苹果一体机')], default=0, verbose_name='部件')),
                ('os', models.CharField(max_length=20, verbose_name='操作系统')),
                ('model', models.CharField(max_length=50, verbose_name='型号')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('location', models.CharField(max_length=20, verbose_name='位置')),
                ('lock', models.IntegerField(choices=[(0, '否'), (1, '是')], verbose_name='机箱锁')),
                ('domain', models.IntegerField(choices=[(0, '否'), (1, '是')], verbose_name='脱域')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asset.User', verbose_name='使用人')),
            ],
            options={
                'verbose_name': 'PC管理',
                'verbose_name_plural': 'PC管理',
                'ordering': ['id'],
            },
        ),
    ]
