# Generated by Django 2.2.5 on 2019-09-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='domain',
            field=models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='脱域'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='lock',
            field=models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='机箱锁'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='操作系统'),
        ),
    ]
