# Generated by Django 2.2.5 on 2019-10-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190930_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='arch',
            field=models.URLField(blank=True, help_text='生产环境应用架构拓扑图', null=True, verbose_name='URL'),
        ),
    ]
