# Generated by Django 2.2.5 on 2019-10-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_surl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='surl',
            field=models.URLField(blank=True, null=True, verbose_name='SURL'),
        ),
    ]
