# Generated by Django 2.2.5 on 2019-10-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191017_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='lang',
            field=models.IntegerField(choices=[(0, 'java'), (1, 'js'), (2, 'nodejs'), (3, 'python')], default=0, verbose_name='语言'),
        ),
    ]
