# Generated by Django 2.2.5 on 2019-11-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_db_middle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db',
            options={'ordering': ('id',), 'verbose_name': '数据库管理', 'verbose_name_plural': '数据库管理'},
        ),
        migrations.AlterModelOptions(
            name='middle',
            options={'ordering': ('id',), 'verbose_name': '中间件管理', 'verbose_name_plural': '中间件管理'},
        ),
    ]
